replicaCount: 2

image:
  repository: cloudketan/node-gitops
  pullPolicy: Always
  tag: "v1"

service:
  type: NodePort
  port: 3000
  nodePort: 32000

ingress:
  enabled: false
  host: node-k8s-status.local
      
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80

autoscaling:
  enabled: false

podLabels: {}
podAnnotations: {}

serviceAccount:
  create: true
  name: ""

httpRoute:
  enabled: false